# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  maven: circleci/maven@0.0.12
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: mule
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_VERSION: 4.3.0
          MULE_APP_NAME: circleci-demo-venkat
          MULE_ENV: SANDBOX
          MULE_WORKER_TYP: MICRO
          MULE_WORKER: 1
    steps:
      - checkout
      - restore_cache:
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - save_cache:
          paths:
            - ~/.m2
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - run:
          name: cloudhub deployment
          command: |
            mvn clean deploy -DmuleDeploy -Danypoint.username=venky2121 -Danypoint.password=Reddy@1357 -Danypoint.environment=Sandbox -Dmule.version=4.3.0
